name: CI
on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.25", "1.24"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build Go ${{ matrix.go }}
        run: go build -v ./...
      - name: Test Go ${{ matrix.go }}
        run: go test  ./... -v
